export const TOPICS = {
    DROP_CONTEXT_LISTENER: 'dropContextListener',
    ADD_CONTEXT_LISTENER: 'addContextListener',
    DROP_INTENT_LISTENER: 'dropIntentListener',
    ADD_INTENT_LISTENER: 'addIntentListener',
    BROADCAST: 'broadcast',
    OPEN: 'open',
    CONTEXT: 'context',
    GET_CURRENT_CONTEXT: 'getCurrentContext',
    GET_OR_CREATE_CHANNEL: 'getOrCreateChannel',
    GET_USER_CHANNELS: 'getUserChannels',
    GET_SYSTEM_CHANNELS: 'getSystemChannels',
    LEAVE_CURRENT_CHANNEL: 'leaveCurrentChannel',
    GET_CURRENT_CHANNEL: 'getCurrentChannel',
    JOIN_CHANNEL: 'joinChannel',
    INTENT: 'intent',
    FIND_INTENT: 'findIntent',
    FIND_INTENTS_BY_CONTEXT: 'findIntentsByContext',
    RAISE_INTENT: 'raiseIntent',
    RAISE_INTENT_FOR_CONTEXT: 'raiseIntentForContext',
    RESOLVE_INTENT: 'resolveIntent',
    GET_INFO: 'getInfo',
  };